# Site Settings
locale                   : "en-US"
title                    : "Akram Ibrahim"
title_separator          : "-"
name                     : &name "Akram Ibrahim"
description              : &description "PhD Candidate in Physics/Computational Materials Science at UMBC"
url                      : https://akram-ibrahim.github.io # the base hostname & protocol for your site
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "Akram-Ibrahim/Akram-Ibrahim.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image


# Site Author
author:
  name             : "Akram Ibrahim"
  avatar           : "profile.jpg" # adjust this with your actual image file
  bio              : "Physics PhD Candidate, specializing in Computational Materials Science"
  location         : "Baltimore, MD"
  employer         :
  pubmed           :
  googlescholar    : "https://scholar.google.com/citations?user=DE8SYKEAAAAJ&hl=en"
  email            : "akram.hafez78@gmail.com"
  github           : "Akram-Ibrahim"
  linkedin         : "akram-ibrahim-92809a123"
  
# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
  

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Whitelist plugins
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
